import { route } from 'next/dist/server/router';
import Head from 'next/head';
import { useRouter } from 'next/router';


const Header = () => {
  const router = useRouter()
  const { locale, locales, defaultLocale } = router;  
  const changeLocale = (e) => {
    e.preventDefault();
    
    // defaultLocale == `en`
    let path = router.pathname
    let arr = path.split('/');
    arr.splice(arr.length - 1); // returns the old array without spliced data
    let normal_path_except_query_data = arr.join('/');
    
    const query_page_value = router.query.page;
    
    let actual_url;    
    
    if(query_page_value != undefined){
      actual_url = normal_path_except_query_data +'/'+query_page_value;
    } else {
      actual_url = normal_path_except_query_data;
    }

    if(e.target.value == 'en'){
      router.push( actual_url,  actual_url, { shallow: true, locale: 'en' })
    } else {
      router.push( actual_url, actual_url, { shallow: true, locale: 'bn' })
    }    
  }

  return(
    <>
      <Head>
        <title>Panda In Adventure</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head> 
      Change Language:
      <select onChange={changeLocale} defaultValue={locale} className='flex p-4 rounded-md border shadow-md'>
        {locales.map( (lang, key) => <option key={key} value={lang}>{lang.toUpperCase()}</option> )}
      </select>     
    </>
  )
}

export default Header;